[versions]
compileSdk = "34"
minSdk = "26"
targetSdk = "34"
versionName = "1.3"
versionCode = "3"

gradleplugin = "8.1.1"

kotlin = "1.9.10"
kotlinx-coroutines = "1.7.3"
ksp = "1.9.10-1.0.13"

androidx-core = "1.10.1"
androidx-appcompat = "1.6.1"
androidx-fragment = "1.6.1"
androidx-lifecycle = "2.6.2"
androidx-contstraintlayout = "2.1.4"
androidx-navigation = "2.7.2"
androidx-splash = "1.0.1"
androidx-camerax = "1.2.3"
androidx-test-junit = "1.1.5"
androidx-test-espresso = "3.5.1"

google-services-plugin = "4.3.15"
google-crashlytics-plguin = "2.9.9"
google-protobuf-plugin = "0.9.3"
google-firebase = "32.2.3"
google-material = "1.9.0"
google-text-recognition = "19.0.0"
google-text-recognition-korean = "16.0.0"

retrofit = "2.9.0"
okhttp = "4.11.0"
junit = "4.13.2"
hilt = "2.48"
timber = "5.0.1"
glide = "4.15.1"
systemuicontroller = "1.0.1"

[libraries]
android-build = { module = "com.android.tools.build:gradle", version.ref = "gradleplugin" }
kotlin-gradle = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
hilt-gradle = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
nav-safeargs-gradle = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref="androidx-navigation"}

kotlin = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlin-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "androidx-contstraintlayout" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "androidx-fragment" }
androidx-splash = { module = "androidx.core:core-splashscreen", version.ref = "androidx-splash" }
androidx-nav-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation"}
androidx-nav-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation"}
androidx-camerax-view = { module = "androidx.camera:camera-view", version.ref="androidx-camerax"}
androidx-camerax-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref="androidx-camerax"}
androidx-camerax-extensions = { module = "androidx.camera:camera-extensions", version.ref="androidx-camerax"}

google-services-gradle = { group = "com.google.gms", name = "google-services", version.ref = "google-services-plugin" }
google-material = { module = "com.google.android.material:material", version.ref = "google-material" }
google-firebase = { module = "com.google.firebase:firebase-bom", version.ref = "google-firebase" }
google-firebase-analytics = { module = "com.google.firebase:firebase-analytics-ktx" }
google-firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics-ktx" }
google-firebase-auth = { module = "com.google.firebase:firebase-auth-ktx" }
google-firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx" }
google-text-recognition = { module = "com.google.android.gms:play-services-mlkit-text-recognition", version.ref = "google-text-recognition"}
google-text-recognition-korean = { module = "com.google.mlkit:text-recognition-korean", version.ref = "google-text-recognition-korean"}
google-crashlytics-gradle = { module = "com.google.firebase:firebase-crashlytics-gradle", version.ref = "google-crashlytics-plguin" }

okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-ksp = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-plugin = { group = "com.google.dagger", name = "hilt-android-gradle-plugin", version.ref = "hilt" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide"}
systemuicontroller = { module = "land.sungbin:systemuicontroller", version.ref = "systemuicontroller" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "androidx-test-espresso" }

[bundles]

androidx = [
    "androidx-appcompat",
    "androidx-constraintlayout",
    "androidx-core",
    "androidx-lifecycle-viewmodel",
    "androidx-fragment",
    "androidx-lifecycle-runtime",
]
androidx-navigation = [ "androidx-nav-fragment", "androidx-nav-ui"]
androidx-camerax = ["androidx-camerax-view", "androidx-camerax-extensions", "androidx-camerax-lifecycle"]
okhttp = ["okhttp", "okhttp-logging-interceptor"]
retrofit = ["retrofit", "retrofit-moshi"]
firebase = [
    "google-firebase-crashlytics",
    "google-firebase-analytics",
    "google-firebase-auth",
    "google-firebase-firestore"
]
text-recognition = ["google-text-recognition", "google-text-recognition-korean"]

[plugins]
android-application = { id = "com.android.application", version.ref = "gradleplugin" }
android-library = { id = "com.android.library", version.ref = "gradleplugin" }
androidx-navigation-safeargs= { id = "androidx.navigation.safeargs.kotlin", version.ref = "androidx-navigation"}
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }
google-firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "google-crashlytics-plguin" }
dagger-hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }